name: Build

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_disptach:

jobs:
  build:
    uses: PlakarKorp/ci-workflows/.github/build/go.yml@build-go
    with:
      target: ./...
      test-option-timeout: 30s
    secrets: inherit
